name: med_shakthi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.6+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  uuid: ^4.5.2
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^6.0.0
  provider: ^6.1.5+1
  onesignal_flutter: ^5.1.2

  # ðŸ”¥ REQUIRED FOR GEMINI API
  http: ^1.2.0

  file_picker: ^10.3.8
  intl: ^0.20.2
  image_picker: ^1.2.1
  google_maps_flutter: 2.5.0
  geolocator: 10.1.0
  geocoding: ^3.0.0
  geocoding_android: ^3.0.0
  cloud_firestore: ^6.1.1
  fl_chart: ^1.1.1
  shared_preferences: ^2.5.4
  package_info_plus: ^9.0.0
  csv: ^6.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  mobile_scanner: ^5.1.1
  firebase_storage: ^13.0.6
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  open_filex: ^4.4.0
  webview_flutter: ^4.13.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/data/
    - .env
